apiVersion: v1
kind: Pod
metadata:
  name: resouce-request
spec:
  containers:
  -
    name: nginx
    image: nginx
    resources:
      requests:
        cpu: 50m
        # 下のような書き方もOK
        # cpu: 1
        # cpu: 0.5
        memory: 8Mi
        # 下のような書き方もOK
        # memory: 512Mi
        # memory: 2Gi
      limits:
        cpu: 200m
        memory: 64Mi