apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-check
spec:
  # Podの起動前に実行されるコンテナ
  # この順番で実行される
  initContainers:
  - name: init
    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      echo Start at `date`; sleep 3; echo End at `date`. ; exit 0
  containers:
  -
    name: app
    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      trap 'echo "Trapped SIGTERM"; sleep 3; echo "See you!"; exit 0' TERM

      echo Start.
      
      while true
      do
          date
          sleep 1
      done
    lifecycle:
      postStart:
        exec:
          command:
          - "sh"
          - "-c"
          - |
            echo hook postStart.
            date
            exit 0
      preStop:
        exec:
          command:
          - "sh"
          - "-c"
          - |
            echo hook preStop.
            date
            exit 0
  restartPolicy: Never
# 以下のエラーが出たためコメントアウト
# ```log
# ValidationError(Pod): unknown field "terminationGracePeriodSeconds" in io.k8s.api.core.v1.Pod;
# ```
# terminationGracePeriodSeconds: 0